### ISSUE TITLE
Halting problem

### ISSUE THREAD

**Issue by DavideWiest** [BosqueLanguage/BosqueCore#154]
I read
> Termination and Bounds analysis -- a static analysis that can prove the termination of a function/task/api and the bounds on the resources it consumes.

this sounds like: Find a solution to the halting problem. That's unsolvable.

**Comment by marron-at-work** [comment]
Hi, you are absolutely correct that in general this problem is unsolvable. So, the goal here is prove these properties as much as possible -- lots of prior work in this space e.g. [terminator](http://www0.cs.ucl.ac.uk/staff/b.cook/pdfs/termination_proofs_for_systems_code.pdf). 

The interesting thing is, that for large numbers of programs, termination is provable. Iteration with decreasing measure or grounded structural recursion, which most code structures match, are conceptually trivial to prove termination for. But trying to do this in an imperative language, like C++ or Java, is actually quite difficult.

For example the loop:
```
vector<int> v = ...; 
for(int i = 0; i < v.size(); ++i) {
...
}
```
Is terminating, since i monotonically increases, if you can prove that `v.size()` doesn't change in the loop body (which is surprisingly hard). 

Similarly the recursive code:
```
class ListNode {
    int v;
    ListNode* next;
};

ListNode* ll = ...;
while(ll != nullptr) {
    if(ll->value == 42) { stdout << "found" << endl;  return; }

    ll = ll->next;
}
```
Is terminating if `ll` is acyclic, otherwise it can get stuck in a loop.

Bosque is in a unique position then as:

1. It does not have loops -- only higher order functors on collections like `l.map(fn(x) => ...)` or `l.find(pred(x) => ...)` which are trivially terminating.
2. There is no mutation so finding monotone termination functions (like in the first example) is a much simpler process.
3. By construction, all data structures are acyclic, so even (structural) recursion is trivially terminating.

So, my questions in this space are, (1) how effective are the simplifications in proving termination in practice (I think they will be very powerful) and (2) can we do even better and provide fixed bounds in addition to just termination.
